
#      datasource:
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/microservices
#        username: root
#        password: pass5678
#        driver-class-name: com.mysql.cj.jdbc.Driver
#
#        jpa:
#          hibernate:
#            ddl-auto: update
#          show-sql : true
#          properties:
#            hibernate:
#              dialect: org.hibernate.dialect.MySQL8Dialect
#





spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor
    username: root
    password: pass5678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect





